spring:
  rabbitmq:
    host: ${RabbitMQ_Host:localhost}
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10

