version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: careerly-db
    environment:
      - POSTGRES_DB=Careerly
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    networks:
      - careerly-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: careerly-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - careerly-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  backend-service:
    build: .
    image: yashzade/careerly-backend
    container_name: careerly-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=Careerly-Backend
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Careerly
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
      - SPRING_JPA_SHOW-SQL=true
      - JWT_SECRETKEY=ofigicjkadgyegfouiasdgf8wtf9asdgwetfp9ewfgidgsugwp7eft87egdpiw9e7ftpgousyfgwe97fte7g8FTWEP9FGLI8FT7Fgol7ge
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME= app.careerly@gmail.com
      - SPRING_MAIL_PASSWORD= fpih pfan qsrs kero
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_VIRTUAL-HOST=/
    networks:
      - careerly-network
    depends_on:
      - postgres
      - rabbitmq

networks:
  careerly-network:

volumes:
  postgres_data:
  rabbitmq_data: